# Generated by Django 4.0.4 on 2022-06-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/profile_pics/%Y/%M/%d', verbose_name='Profile Picture:'),
        ),
    ]
