# Generated by Django 4.0.4 on 2022-08-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dean',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_deans', to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_hod', to='accounts.department'),
        ),
    ]
