# Generated by Django 4.0.4 on 2022-07-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_user_faculty_user_programme_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registry',
        ),
    ]
