# Generated by Django 4.0.4 on 2022-06-24 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title:')),
                ('description', models.TextField(null=True, verbose_name='Description:')),
                ('hod_forward', models.BooleanField(default=False, verbose_name='Forward:')),
                ('hod_solve', models.BooleanField(default=False, verbose_name='Solve:')),
                ('dean_forward', models.BooleanField(default=False, verbose_name='Forward:')),
                ('dean_solve', models.BooleanField(default=False, verbose_name='solve:')),
                ('registry_forward', models.BooleanField(default=False, verbose_name='Forward:')),
                ('registry_solve', models.BooleanField(default=False, verbose_name='Solve:')),
                ('support_repond', models.BooleanField(default=False, verbose_name='Respond:')),
                ('user_repond_text', models.TextField(blank=True, null=True, verbose_name='Respond Text:')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('complainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_complaints', to=settings.AUTH_USER_MODEL)),
                ('forword_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forward_to_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
