# Generated by Django 4.0.4 on 2022-08-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaintsApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='dean_forward',
            new_name='forward',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='hod_solve',
            new_name='solve',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='dean_solve',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='hod_forward',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='registry_forward',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='registry_solve',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolved_complaint',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='support_repond',
        ),
    ]
