# Generated by Django 4.0.4 on 2022-07-20 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaintsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='forword_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forward_to_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
