# Generated by Django 4.0.4 on 2022-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintsApi', '0002_alter_complaint_forword_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_complaint',
            field=models.BooleanField(default=False, verbose_name='resolved:'),
        ),
    ]
