# Generated by Django 4.0.4 on 2022-08-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaintsApi', '0002_rename_dean_forward_complaint_forward_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='forword_to',
            new_name='forward_to',
        ),
    ]
