# Generated by Django 4.0.4 on 2022-08-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_department_and_more'),
        ('complaintsApi', '0004_remove_complaint_forward_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='forward_to_dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forward_to_dean', to='accounts.dean'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='forward_to_it',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forward_to_it', to='accounts.itsupport'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='forward_to_registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forward_to_registry', to='accounts.registry'),
        ),
    ]
