# Generated by Django 4.0.4 on 2022-08-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintsApi', '0005_alter_complaint_forward_to_dean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='forward_to_dean',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='forward_to_it',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='forward_to_registry',
        ),
        migrations.AddField(
            model_name='complaint',
            name='forward_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Forward To:'),
        ),
    ]
