# Generated by Django 4.0.4 on 2022-08-27 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaintsApi', '0006_remove_complaint_forward_to_dean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='forward_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
